title = "TANIT"
baseURL = "https://tanit.consulting"
languageCode = "fr"
theme = "ananke4tanit"
resourceDir = "../resources"

DefaultContentLanguage = "fr"
SectionPagesMenu = "main"
Paginate = 10 
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = "icons/icon.png"
  site_logo = "icons/logo512.svg"
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-gray"
  recent_posts_number = 10
  custom_css = ["css/tanit.css"]

[[params.ananke_socials]]
name = "Twitter"
url = "https://twitter.com/marionbourhis"
[[params.ananke_socials]]
name = "Linkedin"
url = "https://www.linkedin.com/in/marion-bourhis-19737043/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false
